### ISSUE TITLE
My setup suddenly stopped working - won't update $PATH variable

### ISSUE THREAD

**Issue by thornomad** [JeanMertz/chruby-fish#33] opened 2018-04-10 16:23 UTC
`chruby-fish` suddenly stopped working for me ... I'm not sure what changed on my system or what triggered it.  And I'm having a hard time debugging it!  Can you help me figure out what is going wrong ?  

#### Here is an example of what's happening using `fish`:

```fish
~ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
~ source /usr/local/share/chruby/chruby.fish
~ chruby --version
chruby: 0.3.9
chruby-fish: 0.8.1
~ chruby
   ruby-2.3.0
   ruby-2.4.4
   ruby-2.5.0
~ chruby 2.4.4
~ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
~ echo $PATH
/usr/local/bin /usr/bin /bin /usr/sbin /sbin 
```

As you can see above the environmental variables are not being updated -- when I switch my shell to `bash`, however, everything works as expected. 

#### here is an example using `bash`

```bash
:~$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
:~$ source /usr/local/share/chruby/chruby.sh
:~$ chruby --version
chruby: 0.3.9
:~$ chruby
   ruby-2.3.0
   ruby-2.4.4
   ruby-2.5.0
:~$ chruby 2.4.4
:~$ ruby -v
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
:~$ echo $PATH
/Users/damon/.gem/ruby/2.4.4/bin:/Users/damon/.rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/bin:/Users/damon/.rubies/ruby-2.4.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

#### workaround

For now I've had to copy the `$PATH` output from the bash shell and create an alias in fish to load the correct ruby `$PATH` -- this allows me to use the different rubies ... however, as you can imagine, this is not ideal.

Any ideas about how I can go about sorting what went wrong ?  I've tried removing and reinstalling view homebrew but no luck.

Thanks.

PS - I think the only thing I installed between when it was and was not working is VMWare Fusion; which did add a line to the `$PATH` ... but it was in both bash and fish so I'm not sure why one would work and the other not.

**Comment by thornomad** [comment] 2018-04-17 17:57
Hi @JeanMertz - I cropped the path so it wouldn't be so long .... `/Applications/VMware Fusion.app/Contents/Public` is at the end of both (bash and fish) `echo $PATH` commands.  Sorry if that threw you off, was just trying to be concise.

For now, I am manually exporting the path before before I execute the `rails` commands:

```fish
set PATH -gx /Users/damon/.gem/ruby/2.5.0/bin /Users/damon/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/bin /Users/damon/.rubies/ruby-2.5.0/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin; and bundle exec rails server
```

This works ... but am not sure why `chruby 2.5.0` isn't able to do the same thing in fish.

**Comment by JeanMertz** [comment] 2018-04-17 21:31
I checked, but chrubby hasn't been updated, chruby-fish also hasn't needed an update in a long time, so something else must have changed. Did you perhaps recently update your Fish version?

**Comment by thornomad** [comment] 2018-04-22 15:12
I just received a brand new mac (yesterday) and installed it all fresh via homebrew.  Am at versions:

```fish
~ fish --version
fish, version 2.7.1
~ chruby --version
chruby: 0.3.9
chruby-fish: 0.8.1
```

It isn't working for me straight of the box anymore either.   

I tested `bash` again (as in my first post) and that does work.  Are you at the same `fish` version ?  Not sure what else could be interfering.

**Comment by willcosgrove** [comment] 2018-04-30 17:03
I'm having the same issue.  I'm almost certain it was working for me with fish 2.7.1, because I only switched to fish a few months ago, and 2.7.1 came out Dec 2017, which was before I switched.  So unless the version had not been updated in homebrew by the time I switched to fish, I should have been running 2.7.1.

@thornomad It's interesting that you mention installing VMWare Fusion, I also installed that yesterday, and today I just experienced the problem for the first time.  I uninstalled VMWare Fusion yesterday as well.  I'm not sure what the VMWare Fusion install could have done that would break this.

**Comment by willcosgrove** [comment] 2018-04-30 17:07
Wow that ended up being it (for me) @thornomad.  I'm glad you mentioned VMware, I _never_ would have made that connection.

https://communities-gbot.vmware.com/thread/574038

I had to `cd /etc/paths.d` and then `sudo rm com.vmware.fusion.public` which remove the path addition, and fixed the problem for me.

**Comment by databus23** [comment] 2018-04-30 17:08
VMware Fusion injects a path with a space in the PATH environment variable. Maybe that is messing things up. I have fusion installed as well and it’s not working me. Haven‘t tried removing it.

**Comment by thornomad** [comment] 2018-04-30 21:14
Wow - glad we know what's causing it ... I wonder if it's the way `chruby.sh` is handling the `:` to _space_ swapping when it is reading the `$PATH` variable and creating a new one ... I can imagine an unexpected space could be throwing that off.

    set bash_path (echo $PATH | tr ' ' ':')

That would likely break with a space in one of the path variables I would guess ...

**Comment by JeanMertz** [comment] 2018-05-06 10:12
Could any of you having this problem show the (full, but with any sensitive paths scrambled, if you want) output of these three commands:

```
echo $PATH
```

```
printf '%s\n' $PATH
```

```
bash -c "printf '%s\n' \$PATH"
```

**Comment by databus23** [comment] 2018-05-06 18:37
@JeanMertz Here you go.
The third command output looks fishy...

```
>> echo $PATH
/Users/user/bin /Users/user/Development/go/bin /usr/local/bin /usr/local/sbin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/VMware Fusion.app/Contents/Public

>> printf '%s\n' $PATH
/Users/user/bin
/Users/user/Development/go/bin
/usr/local/bin
/usr/local/sbin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Applications/VMware Fusion.app/Contents/Public

>> bash -c "printf '%s\n' \$PATH"
/Users/user/bin:/Users/user/Development/go/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware
Fusion.app/Contents/Public
```

**Comment by JeanMertz** [comment] 2018-05-06 18:54
Thanks @databus23. The first and second one are interesting. I'm guessing in your `.fish` config, you have quotes around the VMWare Fusion path, like `"/Applications/VMware Fusion.app/Contents/Public"`?

I think the easiest fix for this is to make this change in `chruby.fish`:

```diff
- set bash_path (echo $PATH | tr ' ' ':')
+ set bash_path (string join ':' $PATH)
```

Could you see if that works as expected? The only problem is I don't know since when Fish supports the builtin `string join`, but that's a problem for later.

**Comment by databus23** [comment] 2018-05-06 19:17
@JeanMertz I didn't put this Vmware path in my PATH manually. That is happening by installing VMware fusion 10. which drops a file in `/etc/paths.d`:
```
cat /etc/paths.d/com.vmware.fusion.public
/Applications/VMware Fusion.app/Contents/Public
```

Unfortunately `set bash_path (string join ':' $PATH)` does not seem to change anything.

Calling `chruby 2.5.0` still silently fails (exit: 1) and leaves me with the system ruby.

**Comment by databus23** [comment] 2018-05-06 19:45
I think I know what the problem now:
when invoking this in `chruby_use`
```
  bchruby 'chruby_use' $argv $args | read -l ch_ruby_root ch_rubyopt ch_gem_home \
                                         ch_gem_path ch_gem_root ch_path \
                                         ch_ruby_engine ch_ruby_version \
                                         ch_status
```
The whitespace in `ch_path` is causing an "off by one" error when read fills in the variables. (Printing $ch_status yields `2.5.0`)

**Comment by databus23** [comment] 2018-05-06 20:26
Played around a bit:
Setting this before calling `bchruby 'chruby_use' $argv $args | read ...` seems to fix it in my case
```
  set -l args '; echo "$RUBY_ROOT;${RUBYOPT:-_};${GEM_HOME:-_};${GEM_PATH:-_};${GEM_ROOT:-_};$PATH;$RUBY_ENGINE;$RUBY_VERSION;$?"'

  set -l IFS ";"
```
Not sure if `;` is the best separator or if this might break for other setups though.

**Comment by databus23** [comment] 2018-05-07 07:36
I created a PR to track the discovered problems. I think it makes most sense to continue the discussion there now that we know the root cause of the problem.

**Comment by dwaite** [comment] 2018-08-25 03:51
I manually applied this PR and it fixed my issue (also likely due to VMware Fusion)

**Comment by JeanMertz** [comment] 2018-09-13 17:52
Thanks for the pR @databus23 and for the validation @dwaite. I no longer actively develop in Ruby, so I haven't used `chruby-fish` in a long time.

I'll reserve some time to merge the PR this weekend and do a new release. If that solves everything then 🎉, if not, I might consider looking for someone to take stewardship of the project.

I haven't heard any other complaints besides this one though, so hopefully when this is fixed, we'll have a smooth couple of years ahead of us 😄

**Closed** 2018-09-15 11:42 UTC
