### ISSUE TITLE
fish-specific PATH changes get lost when changing ruby versions

### ISSUE THREAD

**Issue by taralbass** [JeanMertz/chruby-fish#31] opened 2017-07-02 19:52 UTC
My `PATH` variable is not being properly maintained when chruby-fish changes ruby versions. In particular, anything added to the `PATH` variable in `config.fish` gets lost.

In the example below, `/home/tbass/chruby_test/bin` is an empty dir that I added to my path just to illustrate the problem.

```
tbass@stardust ~> env | grep "^PATH="
PATH=/home/tbass/chruby_test/bin:/usr/local/sbin:/usr/local/bin:/usr/bin
tbass@stardust ~> chruby 2.4.0
tbass@stardust ~> env | grep "^PATH="
PATH=/home/tbass/.gem/ruby/2.4.0/bin:/home/tbass/.rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/bin:/home/tbass/.rubies/ruby-2.4.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin
tbass@stardust ~> chruby system
tbass@stardust ~> env | grep "^PATH="
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
tbass@stardust ~> 

```

Not that after changing to 2.4.0, `/home/tbass/chruby_test/bin` is no longer in the `PATH`, nor is it there after returning to system ruby.

Here is my `config.fish`:

```
source /usr/local/share/chruby/chruby.fish
source /usr/local/share/chruby/auto.fish

set -x PATH /home/tbass/chruby_test/bin $PATH
```

I played around a bit and I believe the problem is that when the `bchruby` function invokes `bash`, it invokes a login shell, which resets the `PATH` according to the bash login process instead of using the `PATH` that was passed in as part of the environment. So when it extracts the `PATH` back out, it has done more than just apply chruby's modification to the current `PATH`. Instead, it has applied chruby's modification to whatever the bash login `PATH` is, abandoning the original `PATH` altogether.

When I remove the `-l` option to the `bash` call, it seems to work fine for me, but I don't know if there are any other implications for removing it.

**Comment by dalizard** [comment] 2018-04-17 13:12
I am having similar (the same?) problem. I am unable to prepend to _PATH_:
```fish
~ $ cat ~/.config/fish/config.fish | grep PATH
# Add .bin to PATH
set -x PATH ~/.bin /usr/local/sbin $PATH
~ $ echo $PATH
/Users/foo/.gem/ruby/2.5.0/bin /Users/foo/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/bin /Users/foo/.rubies/ruby-2.5.0/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Users/foo/.bin /usr/local/sbin
~ $ fish --version
fish, version 2.7.1
~ $ chruby --version
chruby: 0.3.9
chruby-fish: 0.8.1
~ $ cat ~/.config/fish/config.fish | tail -n 3
# Ruby manager
source /usr/local/share/chruby/chruby.fish
source /usr/local/share/chruby/auto.fish
~ $
```

**Comment by JeanMertz** [comment] 2018-09-15 12:04
I've released a new version with some path-related fixes. If you're still using chruby, I encourage you to try it out. I'll close this issue, but feel free to let me know if the problem isn't fixed. I'm not sure I have the time to investigate this anytime soon, but maybe I can squeeze it in somewhere.

**Comment by der-flo** [comment] 2019-05-17 11:41
I can confirm this problem is NOT fixed, at least not for my configuration:

```
[ -f /usr/local/share/chruby/chruby.fish ]; and source /usr/local/share/chruby/chruby.fish
set -g fish_user_paths /Applications/MacVim.app/Contents/bin $fish_user_paths
```

As soon as I call `chruby`, my custom PATH addition is postfixed instead of prefixed:

```
$echo $PATH
/Applications/MacVim.app/Contents/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin
$ chruby 2.6.3
$ echo $PATH
/Users/<user>/.gem/ruby/2.6.3/bin /Users/<user>/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/bin /Users/<user>/.rubies/ruby-2.6.3/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/MacVim.app/Contents/bin
```

**Comment by JeanMertz** [comment] 2019-05-21 07:45
Thanks for letting me know @der-flo. I've re-opened the issue, but don't have the time right now to investigate. I'll circle back to this when I can.

**Comment by ioquatix** [comment] 2021-05-29 07:32
I'm running into this issue too.

**Closed** 2022-05-17 01:58 UTC
